tempChapter = rb.getChapter('Driving Profile');
tempSection = tempChapter.getSection('Operating points');
tempSection.addChart('scatter','DP_O_1');
tempChart = tempSection.getChart('DP_O_1');
tempChart.setSignals('Epm_nEng','InjCrv_qSetUnBal');
tempChart.addCondition('elapsedTime',' >=',0,0,0);
tempChart.setRange([0,5000],[0 150]);
tempChart.setQuantity(50,5);
tempChart.setPosition(0,0,.5,.666);
tempChart.setAxisProp('Title','Engine operating points','XLabel','Engine speed [rpm]','YLabel','Quantity[mm3/hub]','ZLabel','Frequency [%]','intervalCount',5);
tempChart.setDisplayType('relFrequency');
tempChart.setMarkProp('Size',10);
tempChart.setSignalThresholds(2,[0,0,100,100]);
tempChart.setDisplayThresholds(2,[1,1,1,1]);
tempChapter = rb.getChapter('Driving Profile');
tempSection = tempChapter.getSection('Operating points');
tempSection.addChart('scatter','DP_O_2');
tempChart = tempSection.getChart('DP_O_2');
tempChart.setSignals('VehV_v','InjCrv_qSetUnBal');
tempChart.addCondition('elapsedTime',' >=',0,0,0);
tempChart.setRange([0,250],[0 150]);
tempChart.setQuantity(2,5);
tempChart.setPosition(.5,0,.5,.666);
tempChart.setAxisProp('Title','Engine operating points','XLabel','Vehicle speed [km/h]','YLabel','Quantity[mm3/hub]','ZLabel','Frequency [%]','intervalCount',5);
tempChart.setDisplayType('relFrequency');
tempChart.setMarkProp('Size',10);
tempChart.setSignalThresholds(2,[0,0,100,100]);
tempChart.setDisplayThresholds(2,[1,1,1,1]);
tempChapter = rb.getChapter('Driving Profile');
tempSection = tempChapter.getSection('Operating points');
tempSection.addChart('hist','DP_O_3');
tempChart = tempSection.getChart('DP_O_3');
tempChart.setSignals('Epm_nEng');
tempChart.addCondition('elapsedTime',' >=',0,0,0);
tempChart.setRange([-250,5250]);
tempChart.setQuantity(500);
tempChart.setPosition(0,.666,.25,.333);
tempChart.setAxisProp('Title','Engine Speed','XLabel','Engine speed [rpm]','ShowLegend',0);
tempChart.setDisplayType('percent');
tempChapter = rb.getChapter('Driving Profile');
tempSection = tempChapter.getSection('Operating points');
tempSection.addChart('hist','DP_O_4');
tempChart = tempSection.getChart('DP_O_4');
tempChart.setSignals('InjCrv_qSetUnBal');
tempChart.addCondition('elapsedTime',' >=',0,0,0);
tempChart.setRange([-25,525]);
tempChart.setQuantity(50);
tempChart.setPosition(.25,.666,.25,.333);
tempChart.setAxisProp('Title','Quantity','XLabel','Quantity[mm3/hub]','ShowLegend',0);
tempChart.setDisplayType('percent');
tempChapter = rb.getChapter('Driving Profile');
tempSection = tempChapter.getSection('Operating points');
tempSection.addChart('hist','DP_O_6');
tempChart = tempSection.getChart('DP_O_6');
tempChart.setSignals('VehV_v');
tempChart.addCondition('elapsedTime',' >=',0,0,0);
tempChart.setRange([-5,165]);
tempChart.setQuantity(10);
tempChart.setPosition(.5,.666,.25,.333);
tempChart.setAxisProp('Title','Vehicle Speed','XLabel','Vehicle speed [km/h]','ShowLegend',0);
tempChart.setDisplayType('percent');
tempChapter = rb.getChapter('Driving Profile');
tempSection = tempChapter.getSection('Operating points');
tempSection.addChart('hist','DP_O_7');
tempChart = tempSection.getChart('DP_O_7');
tempChart.setSignals('Tra_numGear');
tempChart.addCondition('elapsedTime',' >=',0,0,0);
tempChart.setRange([-1.5,6.5]);
tempChart.setQuantity(1);
tempChart.setPosition(.75,.666,.25,.333);
tempChart.setAxisProp('Title','Gear','XLabel','Gear [-]','ShowLegend',0);
tempChart.setDisplayType('percent');